---
execute:
  echo: false
format: 
  html: 
    page-layout: article
project:
  type: website
---
::: {style="text-align: center;"}

# About

The Colorado River Atlas is an effort to make information about the history and status of the Colorado River Basin interactiv and easily accessible. 

Existing data resources can often be difficult to access and analyze for the general public, making critical information about the history and future of the United State's most over stressed river out of reach for many. As reservoir levels continue to fall and long-term management of the river remains tenuous, public accessibility to this information becomes increasingly important.

This project seeks to make this information easier to access and interact with, giving people an important resource to inform themselves and others about the challenges facing the Colorado. It began as a personal project, filling in gaps in data presentation and consolidating different resources into one place, and is aiming to grow to include more resources on water usage, land use patterns, water conservation efforts, legal and political issues, science, history and more. 

The CRA is built using Quarto, an open-source scientific and technical publishing system, and published through GitHub Pages. Click on the GitHub icon in the top-right to visit the GitHub repository and explore the scripts used to process data and build the site. 


## Contribute

Want to contribute to this project? Visit the GitHub repo and make a pull request or use the email below to get in contact with your ideas.

## Contact

Send an email to coloradoriveratlas@gmail.com to get in contact with questions, comments and submissions. 

:::
